import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarCategory = (
  label: string,
  dirName: string,
  collapsed = true,
) => ({
  type: 'category' as const,
  label,
  collapsed,
  items: [
    {
      type: 'autogenerated' as const,
      dirName,
    },
  ],
});

const sidebars: SidebarsConfig = {
  pythonSidebar: [
    {
      type: 'category',
      label: 'Python cơ bản',
      collapsed: false,
      items: [
        'python-basics/index',
        sidebarCategory('1. Làm quen Python', 'python-basics/Python-001 Introduce', false),
        sidebarCategory('2. Biến, kiểu dữ liệu và toán tử', 'python-basics/Python-002 Variables'),
        sidebarCategory('3. Toán tử', 'python-basics/Python-003 Operators'),
        sidebarCategory('4. Rẽ nhánh và thuật toán', 'python-basics/Python-004 Conditions'),
        sidebarCategory('5. Vòng lặp', 'python-basics/Python-005 Loops'),
        sidebarCategory('6. Chuỗi', 'python-basics/Python-006 String'),
        sidebarCategory('7. Hàm', 'python-basics/Python-006 Functions'),
        sidebarCategory('8. List, Dictionary, Set, Tuple', 'python-basics/Python-007 List and Dictionary'),
        sidebarCategory('9. Module và dự án nhỏ', 'python-basics/Python-008 Module'),
        sidebarCategory('10. Xử lý ngoại lệ', 'python-basics/Python-009 Exception Processing'),
        sidebarCategory('11. Đọc ghi file', 'python-basics/Python-010 Write Read Files'),
        sidebarCategory('12. Clean Code và PEP 8', 'python-basics/Python-011 Clean Code'),
        sidebarCategory('Ôn tập và kiểm tra', 'python-basics/Python-Basic-Revision'),
      ],
    },
  ],

  pythonGUISidebar: [
    {
      type: 'category',
      label: 'Python GUI với Tkinter',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'python-gui',
        },
      ],
    },
  ],

  pythonAdvancedSidebar: [
    {
      type: 'category',
      label: 'Python OOP nâng cao',
      collapsed: false,
      items: [
        sidebarCategory('1. Nhập môn OOP', 'python-advanced/PythonOOP-001 Introduce', false),
        sidebarCategory('2. Class và Object', 'python-advanced/PythonOOP-002 Class and Object'),
        sidebarCategory('3. Kế thừa', 'python-advanced/PythonOOP-003 Inheritance'),
        sidebarCategory('4. Trừu tượng hóa', 'python-advanced/PythonOOP-004 Abstraction'),
        sidebarCategory('5. Đa hình', 'python-advanced/PythonOOP-005 Polymorphism'),
        sidebarCategory('6. Decorator', 'python-advanced/PythonOOP-006 Decorators'),
        sidebarCategory('7. Tương tác giữa đối tượng', 'python-advanced/PythonOOP-007 Interaction'),
        sidebarCategory('8. Module, package và môi trường', 'python-advanced/PythonOOP-008 Modules'),
        sidebarCategory('9. Exception và debug', 'python-advanced/PythonOOP-009 Exception and Bug Processing'),
        sidebarCategory('10. Design patterns', 'python-advanced/PythonOOP-010 Design Patterns'),
        sidebarCategory('Ôn tập và bài tập tổng hợp', 'python-advanced/PythonOOP-Revision'),
      ],
    },
  ],

  pythonWebSidebar: [
    {
      type: 'category',
      label: 'Lập trình Web với Python Flask',
      collapsed: false,
      items: [
        sidebarCategory('1. HTML nền tảng', 'python-flask/Chương 1 - HTML', false),
        sidebarCategory('2. CSS và responsive', 'python-flask/Chương 2 - CSS'),
        sidebarCategory('3. JavaScript cơ bản', 'python-flask/Chương 3 - JS'),
        sidebarCategory('4. Backend với Flask', 'python-flask/Chương 4 - Flask'),
        sidebarCategory('5. Deploy sản phẩm', 'python-flask/Chương 5- Deploy'),
      ],
    },
  ],

  gitSidebar: [
    {
      type: 'category',
      label: 'Git và quy trình làm việc',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'git',
        },
      ],
    },
  ],

  awsSidebar: [
    {
      type: 'category',
      label: 'AWS cho Developer',
      collapsed: false,
      items: [
        'cloud/aws/readme',
        sidebarCategory('1. Tổng quan AWS', 'cloud/aws/chuong1', false),
        sidebarCategory('2. IAM và bảo mật', 'cloud/aws/chuong2'),
        sidebarCategory('3. Compute và Lambda', 'cloud/aws/chuong3'),
        sidebarCategory('4. API Gateway', 'cloud/aws/chuong4'),
        sidebarCategory('5. Data store', 'cloud/aws/chuong5'),
        sidebarCategory('6. Messaging và Event-driven', 'cloud/aws/chuong6'),
        sidebarCategory('7. Security nâng cao', 'cloud/aws/chuong7'),
        sidebarCategory('8. Deployment, CI/CD và IaC', 'cloud/aws/chuong8'),
        sidebarCategory('9. Monitoring và Troubleshooting', 'cloud/aws/chuong9'),
        sidebarCategory('10. Ôn và luyện DVA C02', 'cloud/aws/chuong10'),

      ],
    },
  ],
};

export default sidebars;
