import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pythonSidebar: [
    {
      type: 'category',
      label: 'Python Basics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'python-basics', // Ensure this folder exists inside "docs"
        },
      ],
    },
    {
      type: 'category',
      label: 'Python Advanced',
      items: [
        {
          type: 'autogenerated',
          dirName: 'python-advanced',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guizero', 
      items: [
        {
          type: 'autogenerated',
          dirName: 'guizero', // Ensure this folder exists inside "docs"
        },
      ],
    }
  ]
};

export default sidebars;
