name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # or the version you need
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy to Firebase
        run: |
          npx firebase deploy --only hosting --project teach4fun --non-interactive
